=== jonathan-weiss/senegal/senegal-example-app/cassiamon-customizing/keyref-definitions/schema/cassiamon-schemagic-schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns="https://cassiamon.ch/cassiamon-schemagic" xmlns:xidref="https://cassiamon.ch/cassiamon-schemagic" elementFormDefault="qualified" targetNamespace="https://cassiamon.ch/cassiamon-schemagic" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- https://www.data2type.de/xml-xslt-xslfo/xml-schema/kontrolle-ueber-namensraeume/namensraeume-und-xpath-ausdrue -->
    <!-- - - - - - - - -       CONCEPT IDENTIFIER ATTRIBUTE     - - - - - - - -->
    <xsd:attributeGroup name="conceptIdentifier">
        <xsd:attribute name="conceptIdentifier" type="xsd:string"/>
    </xsd:attributeGroup>

    <!-- - - - - - - - -       CONFIGURATION AND DEFINITIONS     - - - - - - - -->
    <xsd:element name="cassiamon">
        <xsd:complexType>
            <xsd:sequence maxOccurs="1" minOccurs="1">
                <xsd:element name="definitions">
                    <xsd:complexType>
                        <!-- - - - - - - - -       ROOT CONCEPTS     - - - - - - - -->
                        <xsd:choice maxOccurs="unbounded" minOccurs="0">
                            <xsd:element name="entity" type="entityType"/>
                        </xsd:choice>
                    </xsd:complexType>
                    <xsd:unique name="all-entity-name-key">
                        <xsd:selector xpath="xidref:./entity"/>
                        <xsd:field xpath="@entityName"/>
                    </xsd:unique>
                    <xsd:keyref name="my-entity-key-ref" refer="all-entity-name-key">
                        <xsd:selector xpath="xidref:./entity/entityReferenceAttribute"/>
                        <xsd:field xpath="@referencedEntity"/>
                    </xsd:keyref>

                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>

    </xsd:element>
    <!-- - - - - - - - -       ALL CONCEPTS AS TYPES     - - - - - - - -->
    <xsd:complexType name="entityType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="entitySimpleAttribute" type="entitySimpleAttributeType"/>
            <xsd:element name="entityReferenceAttribute" type="entityReferenceAttributeType"/>
        </xsd:choice>
        <xsd:attributeGroup ref="conceptIdentifier"/>
        <xsd:attributeGroup ref="entityEntityName"/>
    </xsd:complexType>
    <xsd:complexType name="entitySimpleAttributeType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0"/>
        <xsd:attributeGroup ref="conceptIdentifier"/>
        <xsd:attributeGroup ref="entitySimpleAttributeEntityAttributeName"/>
        <xsd:attributeGroup ref="entitySimpleAttributeEntityAttributeType"/>
    </xsd:complexType>
    <xsd:complexType name="entityReferenceAttributeType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0"/>
        <xsd:attributeGroup ref="conceptIdentifier"/>
        <xsd:attributeGroup ref="entityReferenceAttributeReferencedEntity"/>
        <xsd:attributeGroup ref="entityReferenceAttributeEntityReferenceName"/>
    </xsd:complexType>
    <!-- - - - - - - - -       ALL ATTRIBUTES      - - - - - - - -->
    <xsd:attributeGroup name="entityEntityName">
        <xsd:attribute name="entityName" type="xsd:string"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="entitySimpleAttributeEntityAttributeName">
        <xsd:attribute name="entityAttributeName" type="xsd:string"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="entitySimpleAttributeEntityAttributeType">
        <xsd:attribute name="entityAttributeType" type="xsd:string"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="entityReferenceAttributeReferencedEntity">
        <xsd:attribute name="referencedEntity" type="xsd:string"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="entityReferenceAttributeEntityReferenceName">
        <xsd:attribute name="entityReferenceName" type="xsd:string"/>
    </xsd:attributeGroup>
</xsd:schema>

=== jonathan-weiss/senegal/senegal-example-app/cassiamon-customizing/keyref-definitions/cassiamon-customized.xml
<?xml version="1.0" encoding="utf-8" ?>
<cassiamon xmlns="https://cassiamon.ch/cassiamon-schemagic"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://cassiamon.ch/cassiamon-schemagic ./schema/cassiamon-schemagic-schema.xsd">
    <definitions>
        <entity entityName="Person" conceptIdentifier="Person">
            <entitySimpleAttribute entityAttributeName="firstname" entityAttributeType="Text"/>
            <entitySimpleAttribute entityAttributeName="lastname" entityAttributeType="Text"/>
            <entitySimpleAttribute entityAttributeName="nickname" entityAttributeType="Text" conceptIdentifier="foo"/>
            <entityReferenceAttribute entityReferenceName="address" referencedEntity="fdsd"/>
        </entity>
        <entity entityName="Person" conceptIdentifier="Person">
            <entitySimpleAttribute entityAttributeName="street" entityAttributeType="Text"/>
            <entitySimpleAttribute entityAttributeName="zip" entityAttributeType="Text"/> <!-- TODO Change back to IntegerNumber as soon as this is supported -->
        </entity>
        <entity entityName="Department">
            <entitySimpleAttribute entityAttributeName="title" entityAttributeType="Text"/>
        </entity>
        <entity entityName="DepartmentAddress">
            <entitySimpleAttribute entityAttributeName="street" entityAttributeType="Text"/>
            <entitySimpleAttribute entityAttributeName="phone" entityAttributeType="Text"/> <!-- TODO Change back to IntegerNumber as soon as this is supported -->
        </entity>
        <entity entityName="OfficeBrackets">
            <entitySimpleAttribute entityAttributeName="stupidLevel" entityAttributeType="Text"/>
        </entity>
    </definitions>

</cassiamon>
