=== jonathan-weiss/senegal/senegal-code-generator/senegal-example-plugins/definitions/schema/senegal-schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="https://senegal.ch/senegal" elementFormDefault="qualified" targetNamespace="https://senegal.ch/senegal" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="senegal">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="entity"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="entity">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="entityAttribute"/>
            </xs:sequence>
            <xs:attribute name="entityName" type="xs:string"/>
            <xs:attribute name="kotlinModelClassName" type="xs:string"/>
            <xs:attribute name="kotlinModelPackage" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="entityAttribute">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0"/>
            <xs:attribute name="entityAttributeName" type="xs:string"/>
            <xs:attribute name="entityAttributeType">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="TEXT"/>
                        <xs:enumeration value="NUMBER"/>
                        <xs:enumeration value="BOOLEAN"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="kotlinFieldName" type="xs:string"/>
            <xs:attribute name="kotlinFieldType">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="kotlin.String"/>
                        <xs:enumeration value="kotlin.Int"/>
                        <xs:enumeration value="kotlin.Boolean"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jonathan-weiss/senegal/senegal-example-app/customized-code-generator/definitions/customized.xml
<?xml version="1.0" encoding="utf-8" ?>
<senegal xmlns="https://senegal.ch/senegal"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://senegal.ch/senegal ./schema/senegal-schema.xsd"
>
    <configuration kotlinModelTargetBasePath="@{domainPath}" />
    <definitions>
        <entity
                kotlinModelClassName="Person"
                kotlinModelPackage="ch.senegal.person"
                kotlinModelTargetBasePath="@{domainPath}"
        >
            <entityAttribute kotlinFieldName="firstname" kotlinFieldType="kotlin.String"/>
            <entityAttribute kotlinFieldName="lastname" kotlinFieldType="kotlin.String"/>
            <entityAttribute kotlinFieldName="nickname" kotlinFieldType="kotlin.String"/>
        </entity>
        <entity
                kotlinModelClassName="Address"
                kotlinModelPackage="ch.senegal.address"
                kotlinModelTargetBasePath="@{domainPath}"
        >
            <entityAttribute kotlinFieldName="street" kotlinFieldType="kotlin.String"/>
            <entityAttribute kotlinFieldName="zip" kotlinFieldType="kotlin.Int"/>
        </entity>
    </definitions>

</senegal>
